data_dir: /home/bowen/debug/ycbineoat
model_name: textured_simple
model_dir: ""
debug_dir: /home/bowen/debug/BundleTrack/
init_pose_dir: ""
SPDLOG: 2
port: '5555'
seg_port: '1111'
nerf_port: "9999"

segmentation:
  ob_scales: [0.3,0.3,0.3]
  tolerance: 0.03
  bg_dist: 0.01
  bg_dir: /home/bowen/debug/2022-09-07-16-49-22/bg.ply

depth_processing:
  zfar: 2.0
  erode:
    radius: 1
    diff: 0.001
    ratio: 0.8   #if ratio larger than this, depth set to 0
  bilateral_filter:
    radius: 2
    sigma_D: 2
    sigma_R: 100000
  outlier_removal:
    num: 30
    std_mul: 1
  edge_normal_thres: 10  #deg between normal and ray
  denoise_cloud: False

visible_angle: 70   # Angle between normal and point to camera origin within XXX is regarded as visible

bundle:
  num_iter_outter: 7
  num_iter_inner: 5
  window_size: 5  #exclude keyframes, include new frame
  max_BA_frames: 10
  subset_selection_method: normal_orientation_nearest
  depth_association_radius: 5  # 0: findDenseCorr; 1: findDenseCorrNearestNeighbor3D
  non_neighbor_max_rot: 180
  non_neighbor_min_visible: 0.1   # ratio of pixel visible
  icp_pose_rot_thres: 180    # Rotation larger than XX deg is ignored for icp
  w_rpi: 0
  w_p2p: 1
  w_fm: 1
  w_sdf: 0
  w_pm: 0
  robust_delta: 0.005
  min_fm_edges_newframe: 15
  image_downscale: [4]
  feature_edge_dist_thres: 0.01
  feature_edge_normal_thres: 30   # Normal angle should be within this range

keyframe:
  min_interval: 1
  min_feat_num: 0
  min_trans: 0
  min_rot: 5
  min_visible: 1


sift:
  scales: [2,4,8]
  max_match_per_query: 5
  nOctaveLayers: 3
  contrastThreshold: 0.01
  edgeThreshold: 50
  sigma: 1.6

feature_corres:
  mutual: True
  map_points: False
  max_dist_no_neighbor: 0.02
  max_normal_no_neighbor: 45
  max_dist_neighbor: 0.03
  max_normal_neighbor: 45
  suppression_patch_size: 5
  max_view_normal_angle: 180
  min_match_with_ref: 5
  resize: 400

ransac:
  max_iter: 2000
  num_sample: 3
  inlier_dist: 0.015
  inlier_normal_angle: 45
  desired_succ_rate: 0.99
  max_trans_neighbor: 0.03   #ransac model estimated pose shouldnt be too far
  max_rot_deg_neighbor: 30
  max_trans_no_neighbor: 0.02
  max_rot_no_neighbor: 10
  epipolar_thres: 1
  min_match_after_ransac: 5

p2p:
  projective: false
  max_dist: 0.02
  max_normal_angle: 45

sdf_edge:
  max_dist: 0.02

shape:
  res: 0.005
  xrange: [-0.2,0.2]
  yrange: [-0.2,0.2]
  zrange: [-0.2,0.2]
  max_weight: 100
  truncate_dist: 0.005


